version: "3.9"
services:
  app:
    build:
      context: .
      args:
        ENTERPRISE_URL: "${ENTERPRISE_URL}"
        OPENSOURCE_REPO_LIST: "${OPENSOURCE_REPO_LIST}"
        ENTERPRISE_REPO_LIST: "${ENTERPRISE_REPO_LIST}"
        GITHUB_ENTERPRISE_PAT: "${GITHUB_ENTERPRISE_PAT}"
        USERNAME: "${USERNAME}"
        GITHUB_ORG: "${GITHUB_ORG}"
        ENTERPRISE_ORG: "${ENTERPRISE_ORG}"
