resources:
  - name: dwpdigital-terraform-upgrader
    type: registry-image-resource
    source:
      repository: dwpdigital/terraform-upgrader
    check_every: 5m

  - name: ecr-dwpdigital-terraform-upgrader-dev
    .: (( inject meta.resources.ecr-resource ))
    source:
      repository: "terraform-upgrader"

  - name: ecr-dwpdigital-terraform-upgrader
    .: (( inject meta.resources.ecr-resource ))
    source:
      repository: "terraform-upgrader"
      aws_role_arn: arn:aws:iam::((aws_account.management)):role/ci

jobs:
  - name: mirror-dwpdigital-terraform-upgrader-dev
    serial_groups: [terraform-upgrader]
    plan:
      - get: dwpdigital-terraform-upgrader
        trigger: true
        params:
          format: oci
        attempts: 3
      - put: ecr-dwpdigital-terraform-upgrader-dev
        params:
          image: "dwpdigital-terraform-upgrader/image.tar"
        attempts: 3

  - name: mirror-dwpdigital-terraform-upgrader
    serial_groups: [terraform-upgrader]
    plan:
      - get: dwpdigital-terraform-upgrader
        trigger: true
        params:
          format: oci
        attempts: 3
      - put: ecr-dwpdigital-terraform-upgrader
        params:
          image: "dwpdigital-terraform-upgrader/image.tar"
        attempts: 3
