jobs:
  - name: terraform-upgrader-pr
    plan:
      - get: terraform-upgrader-pr
        trigger: true
        version: every
      - put: terraform-upgrader-pr
        params:
          path: terraform-upgrader-pr
          status: pending
      - .: (( inject meta.plan.terraform-bootstrap ))
        input_mapping:
          terraform-upgrader: terraform-upgrader-pr
      - .: (( inject meta.plan.terraform-plan ))
        input_mapping:
          terraform-upgrader: terraform-upgrader-pr
        params:
          TF_WORKSPACE: "management"
          DETAILED_EXITCODE: ""
        on_failure:
          put: terraform-upgrader-pr
          params:
            path: terraform-upgrader-pr
            status: failure
        on_success:
          put: terraform-upgrader-pr
          params:
            path: terraform-upgrader-pr
            status: success
